Week 7/Challenges/eliteChallenge2/main/default/objects/CartItem__c/CartItem__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <label>Cart Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Week 7/Challenges/eliteChallenge2/main/default/objects/CartItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Searching</fullName>
                <default>true</default>
                <label>Searching</label>
            </value>
            <value>
                <fullName>Bought</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Week 7/Challenges/eliteChallenge2/main/default/classes/ShoppingCartController.cls
public with sharing class ShoppingCartController {
  @AuraEnabled(cacheable=true)
  public static ShoppingCartInfo getContextCartItems() {
    if (!Schema.SObjectType.CartItem__c.isAccessible()) {
      throw new AuraHandledException(
        'Error: You do not have permission to view cart items.'
      );
    }

    Id userId = UserInfo.getUserId();
    ShoppingCartInfo returnInfo = new ShoppingCartInfo();
    returnInfo.username = UserInfo.getName();
    returnInfo.items = [
      SELECT Name, Quantity__c, Status__c
      FROM CartItem__c
      WHERE Owner.Id = :userId
    ];

    return returnInfo;
  }

  @AuraEnabled
  public static CartItem__c createCartItem(String cartItemJson) {
    if (!Schema.SObjectType.CartItem__c.isCreateable()) {
      throw new AuraHandledException(
        'Error: You do not have permission to create cart items.'
      );
    }
    CartItem__c newItem = (CartItem__c) JSON.deserializeStrict(
      cartItemJson,
      CartItem__c.class
    );
    insert newItem;
    return newItem;
  }

  @AuraEnabled
  public static CartItem__c updateCartItem(String cartItemJson) {
    if (!Schema.SObjectType.CartItem__c.isUpdateable()) {
      throw new AuraHandledException(
        'Error: You do not have permission to update cart items.'
      );
    }
    try {
      CartItem__c newItem = (CartItem__c) JSON.deserializeStrict(
        cartItemJson,
        CartItem__c.class
      );
      update newItem;
      return newItem;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  public class ShoppingCartInfo {
    @AuraEnabled
    public String username;
    @AuraEnabled
    public List<CartItem__c> items;
  }
}